# name: Docker Image CI

# on:
#   push:
#     branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout source code
#       uses: actions/checkout@v3

#     - name: Build Docker image
#       run: docker build . --file Dockerfile --tag rosagra/practica5:rosa

#     - name: Login to Docker Hub
#       run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}

#     - name: Push Docker image to Docker Hub
#       run: docker push rosagra/practica5:rosa
name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Generate Random Number
        id: random
        run: echo "number=$(echo $RANDOM)" >> $GITHUB_ENV

      - name: Git Semantic Version
        uses: PaulHatch/semantic-version@v4.0.3
        with:
          major_pattern: "major:"
          minor_pattern: "feat:"
          format: "${{ env.VERSION }}-${{ env.random }}"
        env:
          VERSION: ${{ steps.version.outputs.version }}

      - name: Docker Login
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build -t rosagra/practica5:rosa .
          docker build -t rosagra/practica5:latest .

      - name: Push Docker Image
        run: |
          docker push rosagra/practica5:rosa
          docker push rosagra/practica5:latest
